### ISSUE TITLE
End

### ISSUE THREAD

**Issue by forteller** [hirokiky/pilemd#11]
When pressing the End button on the keyboard the normal thing to happen in all text editors and text boxes is for the cursor to jump to the end of the current line. In PileMd it jumps to the end of the current paragraph instead. This disrupts the normal work flow and makes PMD unnecessarily hard to work with.

Hope you'll be able to fix this soon. Thanks for a great program!

**Comment by hirokiky** [comment]
Ok, Done.
This feature will be on 0.9.1 !!
