### ISSUE TITLE
Missing Preview button on Mac.

### ISSUE THREAD

**Issue by ubhisat** [hirokiky/pilemd#19]
Version 0.9.0 (0.9.0)

![image](https://cloud.githubusercontent.com/assets/3360141/15163867/1ea27fa6-16d9-11e6-9695-cb1b54ccead4.png)

**Comment by hirokiky** [comment]
Yes. I removed it. It was annoying and basically I want to remove the preview feature after improving the editor more and more.

**Comment by ubhisat** [comment]
@hirokiky thanks. BTW, I love it. Feedback: I find preview feature very very useful... please do not remove it.

**Comment by hirokiky** [comment]
@ubhisat Hmm, OK. so how about to use Cmd-P short cut key?

**Comment by ubhisat** [comment]
That is fine. Please keep it around.
