### ISSUE TITLE
Ctrl + (Shift +) Arrows doesn't work

### ISSUE THREAD

**Issue by forteller** [hirokiky/pilemd#7]
When I want to move the cursor one word at a time I use Ctrl + arrows, when I want to mark one word at a time I use Ctrl + Shift + arrows. This is standard everywhere you can write anything in Windows and Linux, but does not work for me in PileMD in Ubuntu Gnome 15.10. Please fix this annoying bug in an otherwise really great editor! Thanks! :)

**Comment by hirokiky** [comment]
Thanks for your reply! It will be nice. 
I'll check the reason.

**Comment by hirokiky** [comment]
Done.
I'll release this feature on next minor release (0.9.1). 

Thanks for your great job!  I added you on AUTHORS text as supporters.

**Comment by forteller** [comment]
Thank you! Do you know anything about when the new version might be released? This bug is killing me almost every day! :)
